#!/bin/bash
#Run this commands on the Ubuntu command line.
#Before installing Docker, update the package list and install necessary dependencies:
sudo apt update && sudo apt upgrade -y
sudo apt install -y apt-transport-https ca-certificates curl software-properties-common
#Add Docker’s Official GPG Key to ensure secure package installation. Add Docker’s GPG key:
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
#Add the stable Docker repository to your system:
echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
#Now, update your package list and install Docker:
sudo apt update
sudo apt install -y docker-ce docker-ce-cli containerd.io
#To confirm that Docker is installed and running:
sudo systemctl enable --now docker
sudo systemctl status docker
