filebeat.inputs:
  - type: filestream
    id: syslog-logs
    enabled: true
    paths:
      - /var/log/syslog

  - type: filestream
    id: suricata-logs
    paths:
      - /var/log/suricata/eve.json
    json.keys_under_root: true
    json.add_error_key: true
    json.message_key: log

setup.template.enabled: false
setup.ilm.overwrite: true

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  index: "filebeat-logs-%{+yyyy.MM.dd}"

setup.kibana:
  host: "kibana:5601"

processors:
  - rename:
      fields:
        - from: "event_type"
          to: "suricata.event_type"
      ignore_missing: true

  - dissect:
      tokenizer: "%{timestamp} %{syslog_hostname} %{syslog_program}: %{message}"
      field: "message"
      target_prefix: "syslog"
      ignore_failure: true

filebeat.modules:
  - module: suricata
    eve:
      enabled: true
      var.paths: ["/var/log/suricata/eve.json"]

filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: true
